name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2      
    - name: Define runtime for build
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101    
    - name: Build with dotnet
      run: dotnet build --configuration Release    
    - name: Generate NuGet package
      run: |  
        cd LessPaper.Shared.MinIO
        dotnet pack -c Release 
  
  unit_test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: checkout
      uses: actions/checkout@v2      
    - name: Define runtime for unit_test   
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101      
    - name: Run tests
      run: |
        cd ./LessPaper.Shared.MinIO.UnitTest
        dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./LessPaper.Shared.MinIO.UnitTest/TestResults/coverage.info 

  integration_test:
    runs-on: ubuntu-latest
    needs: [build, unit_test]
    steps:
    - name: checkout
      uses: actions/checkout@v2      
    - name: Define runtime for the integration test   
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101      
    - name: Start minio server
      env:
        MINT_MODE: full
        SERVER_ENDPOINT: 127.0.0.1:9000
        ACCESS_KEY: minioadmin
        SECRET_KEY: minioadmin
        ENABLE_HTTPS: 1
        MINIO_ACCESS_KEY: minioadmin
        MINIO_SECRET_KEY: minioadmin
        SSL_CERT_FILE: /tmp/minio-config/certs/public.crt
      run: |
          wget -O /tmp/minio https://dl.min.io/server/minio/release/linux-amd64/minio
          chmod +x /tmp/minio
          mkdir -p /tmp/minio-config/certs/
          cp LessPaper.Shared.MinIO.IntegrationTest/TestCertificates/* /tmp/minio-config/certs/
          /tmp/minio -C /tmp/minio-config server /tmp/fs/ &
    - name: Create lesspaper bucket
      run: |
          wget -O /tmp/mc  https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x /tmp/mc
          /tmp/mc config host add minio https://127.0.0.1:9000 minioadmin minioadmin
          /tmp/mc mb minio/lesspaper
    - name: Run tests
      run: |  
        cd LessPaper.Shared.MinIO.IntegrationTest
        dotnet test

  publish:
    runs-on: ubuntu-latest
    needs: [build, unit_test, integration_test]
    steps:
    - name: checkout
      uses: actions/checkout@v2      
    - name: Define runtime for publishing 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101        
    - name: Publish to NuGet
      uses: rohith/publish-nuget@v2.2.0
      with:
        PROJECT_FILE_PATH: LessPaper.Shared.MinIO/LessPaper.Shared.MinIO.csproj
        PACKAGE_NAME: LessPaper.Shared.MinIO
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}    